global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.8.104:9090']
  - job_name: 'node1'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.8.104:9100']
  - job_name: 'node2'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.8.105:9100']
